### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by GladXiao** [JasonWiki/recommend#1]
1、函数式编程需要加强，通过看代码看出来还是比较熟悉Java而可能刚接触Scala。
2、RDD操作带来的效率问题需要斟酌提高。

比如在UBCF.scala文件中，在生成user->user矩阵中先用到了groupBy()，然后在合并中用到了reduce()，这是两段代码比较累赘。scala中尽量不要用var，并且对RDD的操作不需要map。

下面是按照你的代码个人的修改的一些想法（两段代码合并为一段），也不能说一定是最好的，只是共同学习。

```
val userMatrixsRDD = itemsUserCollectionRDD.groupBy(_.1).flatMap(
      x =>
        for (
          ri <- x._2.iterator;
          rj <- x._2.iterator
          if ri.id < rj.id
        )
          yield {
            ((ri.id, rj.id), 1L
          }
    )

    val userAndUserMatrixCollection = userMatrixsRDD 
      .reduceByKey((x, y) => x + y)
      .map { x =>
        val ((uid, vid), counts) = x
        (uid, vid, similarity(uid, vid, counts) // similarity是自定义计算相似度的函数
      }
```

**Comment by JasonWiki** [comment]
首先谢谢你, 当时确实会把 JAVA 的 OO 思想带入
还有个因为当时我们 load 进去的文件是比较特殊，需要 map 做下处理，map 和 reduce 确实可以合在一起。
还有个问题就是 userAndUserMatrixCollection 这个集合是在 driver 做的会出现 OOM

**Comment by GladXiao** [comment]
Scala是纯粹的函数式面向对象语言，Java是命令式语言。其实Scala比Java更面向对象，从Scala中函数是一个对象而Java不是可以看出来，并且Java还有基本类型。你编码的习惯是命令式。
至于OOM的问题一般来说你需要增加执行的分区数，比如 reduceByKey((x, y) => x + y) 改成 .reduceByKey((x, y) => x + y， 200)。OOM本质的问题是单个Task对象过多或者过大，我们要做的就是分开多个Task。
